name: Deploy Complex
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true cygnetops/react-test npm test -- --coverage
      - run: docker build -t cygnetops/multi-client ./client
      - run: docker build -t cygnetops/multi-nginx ./nginx
      - run: docker build -t cygnetops/multi-server ./server
      - run: docker build -t cygnetops/multi-worker ./worker
      - run: docker push cygnetops/multi-client
      - run: docker push cygnetops/multi-nginx
      - run: docker push cygnetops/multi-server
      - run: docker push cygnetops/multi-worker
 