name: Deploy Complex
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t simonpcpc/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true simonpcpc/react-test npm test -- --coverage
      - run: docker build -t simonpcpc/multi-client ./client
      - run: docker build -t simonpcpc/multi-nginx ./nginx
      - run: docker build -t simonpcpc/multi-server ./server
      - run: docker build -t simonpcpc/multi-worker ./worker
      - run: docker push simonpcpc/multi-client
      - run: docker push simonpcpc/multi-nginx
      - run: docker push simonpcpc/multi-server
      - run: docker push simonpcpc/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-eu-west-3-279325290250
          region: eu-west-3
          version_label: ${{ github.sha }}
